#!/bin/bash
set -Eeo pipefail

usage() {
    echo "dal-craft-cli snapshots utility (a3cloud kubectl csi volume snapshot compatible)"
    echo "Usage:"
    echo "  snapshots -h                      Display this help message."
    echo "  snapshots list|info               List available k8s volume snapshots."
    echo "  snapshots create                  Create a new k8s volume snapshot."
    echo "  snapshots print-config            Prints a3cloud k8s ConfigMap/backup-env"
    echo "  snapshots init                    NOOP exit 0"
    echo "  snapshots export <snapshot>       NOT IMPLEMENTED, exit 1"
    echo "  snapshots restore <snapshot>      NOT IMPLEMENTED, exit 1"
}

# auto-source the profile (if the was not sourced before)
source ~/.profile || true

# no options supplied?
if [ -z "$1" ]; then
    usage
    exit 1
fi

# Parse options to the `snapshot` command
while getopts ":h" opt; do
    case ${opt} in
    h )
        usage
        exit 0
        ;;
    \? )
    echo "Invalid Option: -$OPTARG" 1>&2
    exit 1
    ;;
    esac
done
shift $((OPTIND -1))

subcommand=$1; shift  # Remove 'snapshot' from the argument list
case "$subcommand" in

    init)
    echo "init (noop)"
    ;;

    list)
    set -Eeox pipefail
    kubectl get vs -lbackup-ns.sh/retain -Lbackup-ns.sh/type,backup-ns.sh/retain,backup-ns.sh/daily,backup-ns.sh/weekly,backup-ns.sh/monthly,backup-ns.sh/delete-after
    ;;

    info)
    set -Eeox pipefail
    kubectl get vs -lbackup-ns.sh/retain -Lbackup-ns.sh/type,backup-ns.sh/retain,backup-ns.sh/daily,backup-ns.sh/weekly,backup-ns.sh/monthly,backup-ns.sh/delete-after
    ;;

    print-config)
    set -Eeox pipefail
    kubectl get configmap backup-env -o yaml
    ;;

    create)
    set -Eeox pipefail
    /usr/bin/backup-ns.sh
    ;;

    export)
    >&2 echo "Export not implemented. Please escalate to aaa operations. Exit 1!"
    exit 1
    ;;

    restore)
    >&2 echo "Export not implemented. Please escalate to aaa operations. Exit 1!"
    exit 1
    ;;

    *)
    usage
    exit 1
    ;;

esac