name: Build only project

on:
  push:
    branches: 
      - "**"
      - "!master"
      - "!main"

jobs:
  build-only:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Downcase GITHUB_REPOSITORY and set as REPO (for docker image name)
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: docker build cli-a3cloud
        run: docker build --file Dockerfile --target cli-a3cloud --tag ${{ env.REPO }}:${{ github.sha }}-a3cloud .

      - name: docker build cli-borgmatic
        run: docker build --file Dockerfile --target cli-borgmatic --tag ${{ env.REPO }}:${{ github.sha }}-borgmatic .
      # - name: trivy scan
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: '${{ env.REPO }}:${{ github.sha }}'
      #     format: 'template'
      #     template: '@/contrib/sarif.tpl'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'
      #     ignore-unfixed: true
