# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Create and publish image -borgmatic

on:
  push:
    tags: "**"
    branches:
      - "master"
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase GITHUB_REPOSITORY and set as REPO (for docker image name)
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO }}
          flavor: |
            latest=auto
            prefix=
            suffix=-borgmatic

      - name: Build and push Docker image cli-borgmatic
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          target: cli-borgmatic
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}-borgmatic
          labels: ${{ steps.meta.outputs.labels }}
